#!/bin/bash

DeleteNewLine () {
#I will remove all the new line in the file $1
  tr -d "\n\r" < "$1" > "$1".temp
  rm -f "$1"
  mv -f "$1".temp "$1"
}

SedTillEndLine () {
#Will substitute what comes after $1 till the end of the line, with $2 in the file $3
#In case the $1 or $2 need to have a single or double quote, put a backslash before it (eg. \")
  sed -i "s+$1$PARTITION_COLUMN.*+$1$2+g" "$3"
}
